Interesting little test case that causes *AXON* to crash. As a result checked in.
The error thrown is this:

  File "/usr/local/lib/python2.4/site-packages/Axon/Component.py", line
237, in __addChild
    child._callOnCloseDown.append(self.unpause)
AttributeError: type object 'ExampleWrapper' has no attribute
'_callOnCloseDown'

Now, given this happens *with* or *without* a correctly initialising
__init__ method in ExampleWrapper, this is particularly intriguing
since it can be easily demonstrated that this attribute *DID* exist
at some point :-)


Michael.